const ACTION_TYPES = {
    //get users
    GET_USERS_ACTION: 'GET_USERS_ACTION',
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_ERROR: 'GET_USERS_ERROR',
    //get user by id
    GET_USER_ACTION: 'GET_USER_ACTION',
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_ERROR: 'GET_USER_ERROR',
    //create new user
    CREATE_USER_ACTION: 'CREATE_USER_ACTION',
    CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_ERROR: 'GET_USER_ERROR',
    //delete user   `
    DELETE_USER_ACTION: 'DELETE_USER_ACTION',
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_ERROR: 'DELETE_USER_ERROR',

    //get products
    GET_PRODUCTS_ACTION: 'GET_PRODUCTS_ACTION',
    GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',
    //get product by id
    GET_PRODUCT_ACTION: 'GET_PRODUCT_ACTION',
    GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_ERROR: 'GET_PRODUCT_ERROR',
    //create new product
    CREATE_PRODUCT_ACTION: 'CREATE_PRODUCT_ACTION',
    CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_ERROR: 'GET_PRODUCT_ERROR',
    //delete product   `
    DELETE_PRODUCT_ACTION: 'DELETE_PRODUCT_ACTION',
    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_ERROR: 'DELETE_PRODUCT_ERROR',
}

export default ACTION_TYPES;